const uint16_t PROGMEM CTRL_BS[] = {LSFT_T(KC_D), LCTL_T(KC_F), COMBO_END};
const uint16_t PROGMEM CTRL_DEL[] = {KC_C, LT(FN,KC_V), COMBO_END};
const uint16_t PROGMEM ESC_ENT[] = {RCTL_T(KC_J), RSFT_T(KC_K), COMBO_END};
const uint16_t PROGMEM SHIFT_TAB[] = {LT(FN,KC_M), KC_COMM, COMBO_END};
const uint16_t PROGMEM CAPS_LOCK[] = {KC_C, KC_COMM, COMBO_END};
const uint16_t PROGMEM LEADER_KEY[] = {LT(FN,KC_V), LT(FN,KC_M), COMBO_END};
const uint16_t PROGMEM MENU_INSERT[] = {LSFT_T(KC_D), RSFT_T(KC_K), COMBO_END};
const uint16_t PROGMEM LIGHT_SWITCH[] = {LCTL_T(KC_F), RCTL_T(KC_J), COMBO_END};
const uint16_t PROGMEM DOUBLE_OPEN[] = {KC_X, KC_C, COMBO_END};
const uint16_t PROGMEM DOUBLE_CLOSE[] = {KC_COMM, KC_DOT, COMBO_END};
const uint16_t PROGMEM SINGLES[] = {RSFT_T(KC_K), RALT_T(KC_L), COMBO_END};
const uint16_t PROGMEM DASHES[] = {LALT_T(KC_S), LSFT_T(KC_D), COMBO_END};
combo_t key_combos[COMBO_COUNT] = {
  COMBO(CTRL_BS, KC_BSPC),
  COMBO(CTRL_DEL, KC_DEL),
  COMBO(ESC_ENT, KC_ENT),
  COMBO(SHIFT_TAB, KC_TAB),
  COMBO(CAPS_LOCK, KC_CAPS),
  COMBO(LEADER_KEY, QK_LEAD),
  COMBO(MENU_INSERT, KC_INS),
  COMBO(LIGHT_SWITCH, LT(0,KC_NO)),
  COMBO(DOUBLE_OPEN, UM(LDOUBLE)),
  COMBO(DOUBLE_CLOSE, UM(RDOUBLE)),
  COMBO(SINGLES, KC_P1),
  COMBO(DASHES, KC_P2) };