#pragma once
#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE
#define NO_ACTION_ONESHOT
#define NO_MUSIC_MODE
#define LAYER_STATE_8BIT
#define USB_MAX_POWER_CONSUMPTION 100
#define ENCODER_RESOLUTION 4
#define ENCODER_A_PINS { B12 }
#define ENCODER_B_PINS { B13 }
#define MOUSEKEY_DELAY 0
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_MAX_SPEED 32
#define MOUSEKEY_MOVE_DELTA 1
#define MOUSEKEY_WHEEL_DELAY 0
#define COMBO_SHOULD_TRIGGER
#define COMBO_COUNT 16
#define PERMISSIVE_HOLD
#define TAP_FLOW_TERM 125
#define AUTO_SHIFT_TIMEOUT 125
#define NO_AUTO_SHIFT_SETUP
#define RETRO_SHIFT 500
#define LEADER_PER_KEY_TIMING
#define LEADER_TIMEOUT 500
#define LEADER_NO_TIMEOUT
#define UNICODE_SELECTED_MODES UNICODE_MODE_WINDOWS
#define RGBLIGHT_EFFECT_TWINKLE
