#pragma once
#define USB_MAX_POWER_CONSUMPTION 100
#define ENCODER_RESOLUTION 4
#define ENCODERS_PAD_A { B12 }
#define ENCODERS_PAD_B { B13 }
#define MOUSEKEY_DELAY 0
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_MAX_SPEED 32
#define MOUSEKEY_MOVE_DELTA 1
#define MOUSEKEY_WHEEL_DELAY 0
#define COMBO_SHOULD_TRIGGER
#define COMBO_COUNT 15
#define PERMISSIVE_HOLD
#define TAPPING_TERM_PER_KEY
#define TAPPING_TERM 160
#define AUTO_SHIFT_TIMEOUT 160
#define NO_AUTO_SHIFT_SETUP
#define RETRO_SHIFT 480
#define LEADER_PER_KEY_TIMING
#define LEADER_TIMEOUT 320
#define LEADER_NO_TIMEOUT
#define UNICODE_SELECTED_MODES UNICODE_MODE_WINDOWS
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_TWINKLE