bool process_record_user(uint16_t keycode, keyrecord_t *record) { switch (keycode) {
  case LT(1,KC_MINS): if (record->tap.count && record->event.pressed) { tap_code(KC_MINS); tap_code(KC_LEFT); } else if (record->event.pressed) { register_unicodemap(DASHEM); tap_code(KC_LEFT); } return false;
  case LT(1,KC_END): if (record->tap.count && record->event.pressed) { tap_code(KC_END); } else if (record->event.pressed) { tap_code(KC_HOME); } return false;
  case LT(1,KC_LEFT): if (record->tap.count && record->event.pressed) { tap_code(KC_LEFT); } else if (record->event.pressed) { tap_code16(C(KC_LEFT)); } return false;
  case LT(1,KC_RGHT): if (record->tap.count && record->event.pressed) { tap_code(KC_RGHT); } else if (record->event.pressed) { tap_code16(C(KC_RGHT)); } return false;
  case LT(1,KC_DEL): if (record->tap.count && record->event.pressed) { tap_code(KC_DEL); } else if (record->event.pressed) { tap_code16(C(KC_DEL)); } return false;
  case LT(1,KC_QUOT): if (record->tap.count && record->event.pressed) { register_unicodemap(ZQS); tap_code(KC_LEFT); } else if (record->event.pressed) { register_unicodemap(ZQD); tap_code(KC_LEFT); } return false;
  case LT(1,KC_BSPC): if (record->tap.count && record->event.pressed) { tap_code(KC_BSPC); } else if (record->event.pressed) { tap_code16(C(KC_BSPC)); } return false;
  case LT(1,KC_SPC): if (record->tap.count && record->event.pressed) { tap_code(KC_SPC); tap_code(KC_LEFT); } else if (record->event.pressed) { tap_code(KC_END); tap_code(KC_ENT); } return false;
  case LT(1,KC_COMM): if (record->tap.count && record->event.pressed) { register_unicodemap(LSINGLE); tap_code(KC_LEFT); } else if (record->event.pressed) { register_unicodemap(ZEL); tap_code(KC_LEFT); } return false;
  case LT(1,KC_DOT): if (record->tap.count && record->event.pressed) { register_unicodemap(ZDOT); tap_code(KC_LEFT); } else if (record->event.pressed) { register_unicodemap(ZELL); tap_code(KC_LEFT); } return false;
  case LT(1,KC_SLSH): if (record->tap.count && record->event.pressed) { register_unicodemap(QUESTION); tap_code(KC_LEFT); } else if (record->event.pressed) { register_unicodemap(ZBANG); tap_code(KC_LEFT); } return false;
  case LT(1,KC_1): if (record->tap.count && record->event.pressed) { register_unicodemap(Z1); tap_code(KC_LEFT); } else if (record->event.pressed) { register_unicodemap(EXCLAIM); tap_code(KC_LEFT); } return false;
  case LT(1,KC_2): if (record->tap.count && record->event.pressed) { register_unicodemap(Z2); tap_code(KC_LEFT); } else if (record->event.pressed) { tap_code16(S(KC_2)); tap_code(KC_LEFT); } return false;
  case LT(1,KC_3): if (record->tap.count && record->event.pressed) { register_unicodemap(Z3); tap_code(KC_LEFT); } else if (record->event.pressed) { tap_code16(S(KC_3)); tap_code(KC_LEFT); } return false;
  case LT(1,KC_4): if (record->tap.count && record->event.pressed) { register_unicodemap(Z4); tap_code(KC_LEFT); } else if (record->event.pressed) { tap_code16(S(KC_4)); tap_code(KC_LEFT); } return false;
  case LT(1,KC_5): if (record->tap.count && record->event.pressed) { tap_code(KC_5); tap_code(KC_LEFT); } else if (record->event.pressed) { tap_code16(S(KC_5)); tap_code(KC_LEFT); } return false;
  case LT(1,KC_6): if (record->tap.count && record->event.pressed) { tap_code(KC_9); tap_code(KC_LEFT); } else if (record->event.pressed) { tap_code16(S(KC_6)); tap_code(KC_LEFT); } return false;
  case LT(1,KC_7): if (record->tap.count && record->event.pressed) { register_unicodemap(Z7); tap_code(KC_LEFT); } else if (record->event.pressed) { register_unicodemap(ZAMP); tap_code(KC_LEFT); } return false;
  case LT(1,KC_8): if (record->tap.count && record->event.pressed) { tap_code(KC_8); tap_code(KC_LEFT); } else if (record->event.pressed) { tap_code16(S(KC_8)); tap_code(KC_LEFT); } return false;
  case LT(1,KC_9): if (record->tap.count && record->event.pressed) { tap_code(KC_6); tap_code(KC_LEFT); } else if (record->event.pressed) { tap_code16(S(KC_0)); tap_code(KC_LEFT); } return false;
  case LT(1,KC_0): if (record->tap.count && record->event.pressed) { tap_code(KC_0); tap_code(KC_LEFT); } else if (record->event.pressed) { tap_code16(S(KC_9)); tap_code(KC_LEFT); } return false;
  case LT(1,KC_A): if (record->tap.count && record->event.pressed) { register_unicodemap(ZA); tap_code(KC_LEFT); } else if (record->event.pressed) { register_unicodemap(ZAA); tap_code(KC_LEFT); } return false;
  case LT(1,KC_B): if (record->tap.count && record->event.pressed) { tap_code(KC_Q); tap_code(KC_LEFT); } else if (record->event.pressed) { register_unicodemap(ZBB); tap_code(KC_LEFT); } return false;
  case LT(1,KC_C): if (record->tap.count && record->event.pressed) { register_unicodemap(ZC); tap_code(KC_LEFT); } else if (record->event.pressed) { register_unicodemap(ZCC); tap_code(KC_LEFT); } return false;
  case LT(1,KC_D): if (record->tap.count && record->event.pressed) { tap_code(KC_P); tap_code(KC_LEFT); } else if (record->event.pressed) { register_unicodemap(ZDD); tap_code(KC_LEFT); } return false;
  case LT(1,KC_E): if (record->tap.count && record->event.pressed) { register_unicodemap(ZE); tap_code(KC_LEFT); } else if (record->event.pressed) { register_unicodemap(ZEE); tap_code(KC_LEFT); } return false;
  case LT(1,KC_F): if (record->tap.count && record->event.pressed) { register_unicodemap(ZF); tap_code(KC_LEFT); } else if (record->event.pressed) { register_unicodemap(ZFF); tap_code(KC_LEFT); } return false;
  case LT(1,KC_G): if (record->tap.count && record->event.pressed) { register_unicodemap(ZG); tap_code(KC_LEFT); } else if (record->event.pressed) { register_unicodemap(ZGG); tap_code(KC_LEFT); } return false;
  case LT(1,KC_H): if (record->tap.count && record->event.pressed) { register_unicodemap(ZH); tap_code(KC_LEFT); } else if (record->event.pressed) { tap_code16(S(KC_H)); tap_code(KC_LEFT); } return false;
  case LT(1,KC_I): if (record->tap.count && record->event.pressed) { register_unicodemap(ZI); tap_code(KC_LEFT); } else if (record->event.pressed) { tap_code16(S(KC_I)); tap_code(KC_LEFT); } return false;
  case LT(1,KC_J): if (record->tap.count && record->event.pressed) { register_unicodemap(ZJ); register_unicodemap(ZJDOT); tap_code(KC_HOME); } else if (record->event.pressed) { register_unicodemap(ZJJ); tap_code(KC_LEFT); } return false;
  case LT(1,KC_K): if (record->tap.count && record->event.pressed) { register_unicodemap(ZK); tap_code(KC_LEFT); } else if (record->event.pressed) { register_unicodemap(ZKK); tap_code(KC_LEFT); } return false;
  case LT(1,KC_L): if (record->tap.count && record->event.pressed) { register_unicodemap(ZL); tap_code(KC_LEFT); } else if (record->event.pressed) { register_unicodemap(ZLL); tap_code(KC_LEFT); } return false;
  case LT(1,KC_M): if (record->tap.count && record->event.pressed) { register_unicodemap(ZM); tap_code(KC_LEFT); } else if (record->event.pressed) { register_unicodemap(ZMM); tap_code(KC_LEFT); } return false;
  case LT(1,KC_N): if (record->tap.count && record->event.pressed) { tap_code(KC_U); tap_code(KC_LEFT); } else if (record->event.pressed) { tap_code16(S(KC_N)); tap_code(KC_LEFT); } return false;
  case LT(1,KC_O): if (record->tap.count && record->event.pressed) { tap_code(KC_O); tap_code(KC_LEFT); } else if (record->event.pressed) { tap_code16(S(KC_O)); tap_code(KC_LEFT); } return false;
  case LT(1,KC_P): if (record->tap.count && record->event.pressed) { tap_code(KC_D); tap_code(KC_LEFT); } else if (record->event.pressed) { register_unicodemap(ZPP); tap_code(KC_LEFT); } return false;
  case LT(1,KC_Q): if (record->tap.count && record->event.pressed) { tap_code(KC_B); tap_code(KC_LEFT); } else if (record->event.pressed) { register_unicodemap(OGRAVECAP); tap_code(KC_LEFT); } return false;
  case LT(1,KC_R): if (record->tap.count && record->event.pressed) { register_unicodemap(ZR); tap_code(KC_LEFT); } else if (record->event.pressed) { register_unicodemap(ZRR); tap_code(KC_LEFT); } return false;
  case LT(1,KC_S): if (record->tap.count && record->event.pressed) { tap_code(KC_S); tap_code(KC_LEFT); } else if (record->event.pressed) { tap_code16(S(KC_S)); tap_code(KC_LEFT); } return false;
  case LT(1,KC_T): if (record->tap.count && record->event.pressed) { register_unicodemap(ZT); tap_code(KC_LEFT); } else if (record->event.pressed) { register_unicodemap(ZTT); tap_code(KC_LEFT); } return false;
  case LT(1,KC_U): if (record->tap.count && record->event.pressed) { tap_code(KC_N); tap_code(KC_LEFT); } else if (record->event.pressed) { register_unicodemap(ZUU); tap_code(KC_LEFT); } return false;
  case LT(1,KC_V): if (record->tap.count && record->event.pressed) { register_unicodemap(ZV); tap_code(KC_LEFT); } else if (record->event.pressed) { register_unicodemap(ZVV); tap_code(KC_LEFT); } return false;
  case LT(1,KC_W): if (record->tap.count && record->event.pressed) { register_unicodemap(ZW); tap_code(KC_LEFT); } else if (record->event.pressed) { tap_code16(S(KC_M)); tap_code(KC_LEFT); } return false;
  case LT(1,KC_X): if (record->tap.count && record->event.pressed) { tap_code(KC_X); tap_code(KC_LEFT); } else if (record->event.pressed) { tap_code16(S(KC_X)); tap_code(KC_LEFT); } return false;
  case LT(1,KC_Y): if (record->tap.count && record->event.pressed) { register_unicodemap(ZY); tap_code(KC_LEFT); } else if (record->event.pressed) { register_unicodemap(ZYY); tap_code(KC_LEFT); } return false;
  case LT(1,KC_Z): if (record->tap.count && record->event.pressed) { tap_code(KC_Z); tap_code(KC_LEFT); } else if (record->event.pressed) { tap_code16(S(KC_Z)); tap_code(KC_LEFT); } return false;
  case LT(0,KC_NO): if (record->tap.count && record->event.pressed) { tap_code16(LSA(KC_ESC)); } else if (record->event.pressed) { rgblight_toggle_noeeprom(); } return false;
  case RCTL_T(BASE): if (record->tap.count && record->event.pressed) { clear_mods(); set_single_default_layer(BASE); return false; }
  default: return true; } };